### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dwalker-va** [dwalker-va/vibezy#3]
- [ ] /feedback API support
- [ ] /feedback/:id API support
- [ ] /engagement API support

Have a suggestion? Please create a new issue.
